baseURL: "https://blog.bwsd.dev"
timezone: "Africa/Johannesburg"
languageCode: en-us

title: Blog of Barry Wasdell
canonifyURLs: true
summaryLength: 30
enableRobotsTXT: false
disableHugoGeneratorInject: true
enableInlineShortcodes: true

params:
  AuthorName: Barry Wasdell
  AuthorEmail: barry@bwsd.dev
  Description: "Barry's Blog"

disableKinds:
  - taxonomy
  - taxonomyTerm

outputs:
  archive:
    - HTML
    - RSS
  page:
    - HTML
    - RSS

markup:
  blackfriday:
  highlight:
    codeFences: false
    style: ""
    guessSyntax: false
    tabWidth: 2
    noClasses: true

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - publishDate
  publishDate:
    - publishDate
    - date

menu:
  nav:
    - name: Archive
      url: /
      weight: -100
    - name: About
      url: /about
      weight: -90
    - name: GitHub
      url: https://github.com/bwsd0
      weight: -70
