#! /bin/bash
# Convenience script for exporting AWS credentials

cp ~/.aws/credentials /tmp
echo "$(tail -n +2 /tmp/credentials)" > /tmp/credentials
. /tmp/credentials

# These environment variables need to be set before running deploy.sh
echo "export AWS_ACCESS_KEY="$aws_access_key_id""
echo "export AWS_SECRET_KEY="$aws_secret_access_key""
echo "export AWS_S3_BUCKET=blog.bwasd.io"
echo "export AWS_CF_DISTRIBUTION_ID=E23YF6DSXOG9YG"
