#! /bin/bash
# Convenience script for exporting AWS credentials

cp ~/.aws/credentials /tmp
echo "$(tail -n +2 /tmp/credentials)" > /tmp/credentials
. /tmp/credentials

echo "export AWS_ACCESS_KEY="$aws_access_key_id""
echo "export AWS_SECRET_KEY="$aws_secret_access_key""
