baseURL: 'https://blog.bwsd.dev'
languageCode: en-us
title: Blog of Barry Wasdell
canonifyURLs: false
disableKinds:
  - taxonomy
  - taxonomyTerm
summaryLength: 30
enableRobotsTXT: false
disableHugoGeneratorInject: true
enableInlineShortcodes: true
params:
  AuthorName: Barry Wasdell
  AuthorEmail: barry@bwsd.dev
  Description: "Barry's blog"
markup:
  goldmark:
  highlight:
    codeFences: false
    style: ""
    guessSyntax: false
    tabWidth: 2
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - ':git'
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
outputs:
  page:
    - HTML
    - RSS
menu:
  nav:
    - name: Home
      url: /
      weight: -100
    - name: Feed
      url: /index.xml
      weight: -90
    - name: About
      url: /about
      weight: -70
    - name: Code
      url: https://git.bwsd.dev
      weight: -30
